name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Deploy to Firebase Hosting (Live)
      if: github.ref == 'refs/heads/main'
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NISHIMURA_SOUKEN }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > $HOME/gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
        echo "Testing authentication..."
        firebase projects:list --project nishimura-souken
        echo "Deploying to Firebase Hosting..."
        firebase deploy --only hosting --project nishimura-souken
    
    - name: Deploy Preview Channel
      if: github.event_name == 'pull_request'
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NISHIMURA_SOUKEN }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > $HOME/gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
        firebase hosting:channel:deploy pr-${{ github.event.number }} --expires 7d --project nishimura-souken